apiVersion: v1
kind: Pod
metadata:
  name: anirudh-pod
  labels:
    app: nginx-demo
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sh", "-c", "exit 1"]
